### ISSUE TITLE
Частая авторизация

### ISSUE THREAD

**Issue by Alexkurd** [itfrogs/wa-wacab#4]
Для информации посмотрите частичное решение с сохранением в сессию [Cookie 2 session](https://github.com/Alexkurd/wacab/commit/6ffc9a752dbd94cc029dafaa1eaa60d6c6c48f4f)

Единственное, что к нему необходимо добавить, это проверку на получение ответа в случае когда авторизация истекла и надо её обновить.

**Comment by pvlm** [comment]
Алексей, спасибо!  Чуть исправлено и внедрено.:)
upd Правда сервер 301/302 никак не возвращает, всегда 200 вроде, но и это не беда.
